//
//  ListDogsInteractor.swift
//  DogsOut
//
//  Created by ASBEL PARRA on 11/8/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListDogsBusinessLogic
{
  func doSomething(request: ListDogs.Something.Request)
}

protocol ListDogsDataStore
{
  //var name: String { get set }
}

class ListDogsInteractor: ListDogsBusinessLogic, ListDogsDataStore
{
  var presenter: ListDogsPresentationLogic?
  var worker: ListDogsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListDogs.Something.Request)
  {
    worker = ListDogsWorker()
    worker?.doSomeWork()
    
    let response = ListDogs.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
