//
//  ListDogsInteractorTests.swift
//  DogsOut
//
//  Created by ASBEL PARRA on 11/9/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsOut
import XCTest

class ListDogsInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListDogsInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListDogsInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListDogsInteractor()
  {
    sut = ListDogsInteractor()
  }
  
  // MARK: Test doubles
  
  class ListDogsPresentationLogicSpy: ListDogsPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: ListDogs.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = ListDogsPresentationLogicSpy()
    sut.presenter = spy
    let request = ListDogs.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
