//
//  ListDogsWorkerTests.swift
//  DogsOut
//
//  Created by ASBEL PARRA on 11/9/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsOut
import XCTest

class ListDogsWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListDogsWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListDogsWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListDogsWorker()
  {
    sut = ListDogsWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
