//
//  BreedsImagesPresenterTests.swift
//  DogsOut
//
//  Created by ASBEL PARRA on 11/9/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsOut
import XCTest

class BreedsImagesPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: BreedsImagesPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupBreedsImagesPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupBreedsImagesPresenter()
  {
    sut = BreedsImagesPresenter()
  }
  
  // MARK: Test doubles
  
  class BreedsImagesDisplayLogicSpy: BreedsImagesDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: BreedsImages.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = BreedsImagesDisplayLogicSpy()
    sut.viewController = spy
    let response = BreedsImages.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
