//
//  BreedsImagesInteractor.swift
//  DogsOut
//
//  Created by ASBEL PARRA on 11/8/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BreedsImagesBusinessLogic
{
  func doSomething(request: BreedsImages.Something.Request)
}

protocol BreedsImagesDataStore
{
  //var name: String { get set }
}

class BreedsImagesInteractor: BreedsImagesBusinessLogic, BreedsImagesDataStore
{
  var presenter: BreedsImagesPresentationLogic?
  var worker: BreedsImagesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BreedsImages.Something.Request)
  {
    worker = BreedsImagesWorker()
    worker?.doSomeWork()
    
    let response = BreedsImages.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
